name: Feature request
description: Propose a change or new feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: Risks and tradeoffs
